version: "3.8"

services:
  api:
    build: .
    container_name: kanban_api
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - kanban_network

  db:
    image: postgres:16
    container_name: kanban_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - kanban_network

networks:
  kanban_network:

volumes:
  postgres_data:
